### ISSUE TITLE
cross compile for aarch64

### ISSUE THREAD

**Issue by xiongoal** [embedthis/appweb#644]
### Problem Description:

Hi, I croess compile v7.1.0 for aarch64 success, but run failed!

Here is my steps:
1. cp project/appweb-linux-default.mk project/appweb-linux-aarch64.mk
2. vim project/appweb-linux-aarch64
```bash
ARCH := aarch64
CC_AARCH := aarch64
OS := linux
CC := aarch64-linux-gnu-gcc
AR := aarch64-linux-gnu-ar
``` 
3. make -f project/appweb-linux-gnu-gcc
4. copy the build/linux-aarch64-defualt to my armv8 device
5. run ./appweb -v on my device
```bash
segmentation fault (core dumped)
```

here is gdb info
```bash
(gdb) run
Starting program: /home/wenbo/compile/appweb-7.1.0/build/linux-aarch64-default/bin/./appweb 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x0000ffffbe6d25b0 in allocMem (required=80) at src/mpr/mprLib.c:535
535	                        fp->prev->next = fp->next;
Missing separate debuginfos, use: debuginfo-install glibc-2.17-222.el7.aarch64
(gdb) where
#0  0x0000ffffbe6d25b0 in allocMem (required=80) at src/mpr/mprLib.c:535
#1  0x0000ffffbe6d1dc8 in mprAllocMem (usize=64, flags=1) at src/mpr/mprLib.c:329
#2  0x0000ffffbe6e16f4 in mprCreateCond () at src/mpr/mprLib.c:7199
#3  0x0000ffffbe6d1bc4 in mprCreateMemService (manager=0xffffbe6d64fc <manageMpr>, flags=0) at src/mpr/mprLib.c:273
#4  0x0000ffffbe6d6210 in mprCreate (argc=1, argv=0xfffffffff408, flags=0) at src/mpr/mprLib.c:2589
#5  0x0000000000401fb4 in main (argc=1, argv=0xfffffffff408, envp=0xfffffffff418) at src/server/appweb.c:102
```

**Comment by dev-embedthis** [comment]
Sounds like something in the compile went astray. What were the compile switches 

make SHOW=1
